-- 1. Confirm all PL/SQL objects compiled successfully
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('PROCEDURE','FUNCTION','TRIGGER')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

-- Expected: STATUS = 'VALID' for all 8 objects

-- 2. Test FN_GET_MATCH_SCORE directly
SELECT FN_GET_MATCH_SCORE(1, 1) AS SCORE FROM DUAL;

-- 3. Test FN_IS_PROFILE_COMPLETE directly
SELECT FN_IS_PROFILE_COMPLETE(1) AS COMPLETE FROM DUAL;

-- 4. Test FN_GET_APPLICATION_COUNT directly
SELECT FN_GET_APPLICATION_COUNT(1) AS APP_COUNT FROM DUAL;

-- 5. Test SP_UPDATE_APPLICATION_STATUS directly
DECLARE
    v_result VARCHAR2(200);
BEGIN
    SP_UPDATE_APPLICATION_STATUS(1, 'Reviewed', 1, v_result);
    DBMS_OUTPUT.PUT_LINE('Result: ' || v_result);
END;
/

-- 6. Confirm trigger fired — check AUDIT_LOG after the above
SELECT * FROM AUDIT_LOG ORDER BY ACTION_TIME DESC;

-- 7. Test SP_GENERATE_RECOMMENDATIONS directly
DECLARE
    v_result VARCHAR2(500);
BEGIN
    SP_GENERATE_RECOMMENDATIONS(NULL, v_result);
    DBMS_OUTPUT.PUT_LINE('Result: ' || v_result);
END;
/
-- 8. Confirm recommendations were generated
SELECT COUNT(*) FROM RECOMMENDATIONS;