-- Connect as SYSDBA first
CREATE USER careerbridge IDENTIFIED BY 2022;

GRANT CONNECT, RESOURCE, DBA TO careerbridge;
GRANT CREATE SESSION TO careerbridge;
GRANT UNLIMITED TABLESPACE TO careerbridge;
GRANT CREATE VIEW TO careerbridge;
GRANT CREATE SEQUENCE TO careerbridge;
GRANT CREATE TRIGGER TO careerbridge;
GRANT CREATE PROCEDURE TO careerbridge;


-- To make migration files ... Rest in databse/migrations

-- Run in SQL Developer to wipe all demo data (keeps admin + skills)
DELETE FROM AUDIT_LOG;
DELETE FROM NOTIFICATIONS;
DELETE FROM RECOMMENDATIONS;
DELETE FROM INTERVIEWS;
DELETE FROM APPLICATIONS;
DELETE FROM INTERNSHIP_SKILLS;
DELETE FROM INTERNSHIPS;
DELETE FROM STUDENT_SKILLS;
DELETE FROM STUDENTS WHERE USER_ID != 1;
DELETE FROM COMPANIES;
DELETE FROM USERS WHERE ROLE != 'admin';
COMMIT;