-- Admin Dashboard and Reporting System
-- View 1: Application pipeline summary per internship
CREATE OR REPLACE VIEW VW_APPLICATION_SUMMARY AS
SELECT
    i.INTERNSHIP_ID,
    i.TITLE,
    i.STATUS         AS INTERNSHIP_STATUS,
    c.COMPANY_NAME,
    COUNT(a.APPLICATION_ID)                                             AS TOTAL_APPLICATIONS,
    SUM(CASE WHEN a.STATUS = 'Pending'     THEN 1 ELSE 0 END)          AS PENDING,
    SUM(CASE WHEN a.STATUS = 'Reviewed'    THEN 1 ELSE 0 END)          AS REVIEWED,
    SUM(CASE WHEN a.STATUS = 'Shortlisted' THEN 1 ELSE 0 END)          AS SHORTLISTED,
    SUM(CASE WHEN a.STATUS = 'Interview'   THEN 1 ELSE 0 END)          AS INTERVIEW_COUNT,
    SUM(CASE WHEN a.STATUS = 'Accepted'    THEN 1 ELSE 0 END)          AS ACCEPTED,
    SUM(CASE WHEN a.STATUS = 'Rejected'    THEN 1 ELSE 0 END)          AS REJECTED
FROM INTERNSHIPS i
INNER JOIN COMPANIES c    ON i.COMPANY_ID    = c.COMPANY_ID
LEFT  JOIN APPLICATIONS a ON i.INTERNSHIP_ID = a.INTERNSHIP_ID
GROUP BY i.INTERNSHIP_ID, i.TITLE, i.STATUS, c.COMPANY_NAME;


-- View 2: Student placement report
CREATE OR REPLACE VIEW VW_STUDENT_PLACEMENT AS
SELECT
    s.STUDENT_ID,
    s.FIRST_NAME || ' ' || s.LAST_NAME                                  AS STUDENT_NAME,
    s.DEPARTMENT,
    s.UNIVERSITY,
    s.GPA,
    COUNT(a.APPLICATION_ID)                                              AS TOTAL_APPLIED,
    SUM(CASE WHEN a.STATUS = 'Accepted' THEN 1 ELSE 0 END)              AS PLACEMENTS,
    CASE
        WHEN COUNT(a.APPLICATION_ID) > 0
        THEN ROUND(
            SUM(CASE WHEN a.STATUS = 'Accepted' THEN 1 ELSE 0 END)
            / COUNT(a.APPLICATION_ID) * 100, 1)
        ELSE 0
    END                                                                  AS PLACEMENT_RATE_PCT
FROM STUDENTS s
LEFT JOIN APPLICATIONS a ON s.STUDENT_ID = a.STUDENT_ID
GROUP BY s.STUDENT_ID, s.FIRST_NAME, s.LAST_NAME,
         s.DEPARTMENT, s.UNIVERSITY, s.GPA;


-- View 3: Skill demand report
CREATE OR REPLACE VIEW VW_SKILL_DEMAND AS
SELECT
    sk.SKILL_ID,
    sk.SKILL_NAME,
    sk.CATEGORY,
    COUNT(DISTINCT ins.INTERNSHIP_ID)  AS REQUIRED_BY_INTERNSHIPS,
    COUNT(DISTINCT ss.STUDENT_ID)      AS STUDENTS_WITH_SKILL
FROM SKILLS sk
LEFT JOIN INTERNSHIP_SKILLS ins ON sk.SKILL_ID = ins.SKILL_ID
LEFT JOIN STUDENT_SKILLS    ss  ON sk.SKILL_ID = ss.SKILL_ID
GROUP BY sk.SKILL_ID, sk.SKILL_NAME, sk.CATEGORY
ORDER BY REQUIRED_BY_INTERNSHIPS DESC;
